#!/usr/bin/env bash
# cspell:ignore Vercel
# Regenerate apps/api/.env (local scripts/ETL) and apps/api/.dev.vars (wrangler dev)
# from the `pass` password store. No secret is echoed to stdout.
#
# Required pass entries:
#   neon/fims-wallet          pooled DATABASE_URL (line 1)
#   neon/fims-wallet-direct   direct DATABASE_URL (line 1)
#   fims/postgres-url         legacy Vercel Postgres URL
#   fims/spreadsheet-id       legacy Google spreadsheet ID
#   fims/firebase             api key (line 1) + "project_id:" / "app_id:" lines
#   google/api-key            Google API key for the Sheets reader
set -euo pipefail

cd "$(dirname "$0")/../apps/api"

field() { pass show "$1" | sed -n "s/^$2: //p"; } # metadata line from a multiline entry

DATABASE_URL=$(pass show neon/fims-wallet)
DATABASE_URL_DIRECT=$(pass show neon/fims-wallet-direct)
POSTGRES_URL=$(pass show fims/postgres-url)
GOOGLE_SPREADSHEET_ID=$(pass show fims/spreadsheet-id)
FIREBASE_API_KEY=$(pass show fims/firebase | head -1)
FIREBASE_PROJECT_ID=$(field fims/firebase project_id)
FIREBASE_APP_ID=$(field fims/firebase app_id)
GOOGLE_API_KEY=$(pass show google/api-key)

cat >.env <<EOF
# Generated by scripts/pull-secrets.sh — do not commit
DATABASE_URL=$DATABASE_URL
DATABASE_URL_DIRECT=$DATABASE_URL_DIRECT

# Legacy sources — only needed for scripts/migrate.ts
POSTGRES_URL=$POSTGRES_URL
GOOGLE_API_KEY=$GOOGLE_API_KEY
GOOGLE_SPREADSHEET_ID=$GOOGLE_SPREADSHEET_ID
FIREBASE_API_KEY=$FIREBASE_API_KEY
FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
FIREBASE_APP_ID=$FIREBASE_APP_ID
EOF

printf 'DATABASE_URL=%s\n' "$DATABASE_URL" >.dev.vars

echo "wrote apps/api/.env and apps/api/.dev.vars ($(wc -l <.env) + $(wc -l <.dev.vars) lines)"
